### ISSUE TITLE
ALERT MODEL CHANGE --> Wavelength Range in LightSourceCoupling moved to Tier 3

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#228]
Assign Tier 3 to LightSourceCoupling/WavelengthRange

**Comment by Akramhar** [comment]
should be fixed in 0.35

**Comment by strambc** [comment]
this was not fixed WavelengthRange remains apparently at Tier 2

**Comment by Akramhar** [comment]
should be done in 0.37

**Comment by strambc** [comment]
Checked again with v041-2 and for LightGuide WavelengthRange appears in TIer 2
