### ISSUE TITLE
Channel settings: after saving Channel, went back to Edit and LightPath + Fluorophore is not accessible anymore

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReact#262]
**BEFORE** 

![image](https://user-images.githubusercontent.com/4050585/111104906-1ad0a700-8528-11eb-9130-2a4d4ab83312.png)

**AFTER**

![image](https://user-images.githubusercontent.com/4050585/111104736-b7467980-8527-11eb-91d7-80d6dbf26053.png)

**Comment by Akramhar** [comment]
should be solved in 0.37

**Comment by strambc** [comment]
NOT SOLVED!
Cannot access Fluorophore anymore even when Channel is not validated

**Comment by strambc** [comment]
![image](https://user-images.githubusercontent.com/4050585/111335575-dee23280-864a-11eb-81ac-0797c3603551.png)

**Comment by strambc** [comment]
![image](https://user-images.githubusercontent.com/4050585/111335662-f15c6c00-864a-11eb-845c-9b4faf846ab9.png)

**Comment by Akramhar** [comment]
should be solved in 0.38

**Comment by strambc** [comment]
@Akramhar  NOT SOLVED

**Comment by Akramhar** [comment]
should be solved, problem may arise with older savefiles
